CREATE TABLE [User] (
    ID VARCHAR(36) PRIMARY KEY,
    USERNAME NVARCHAR(50) NOT NULL UNIQUE,
    PASSWORD NVARCHAR(60) NOT NULL,
    ROLE NVARCHAR(10) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Country (
    ID VARCHAR(36) PRIMARY KEY,
    COUNTRY_NAME NVARCHAR(255) NOT NULL
);

CREATE TABLE Genre (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL
);

CREATE TABLE Movie (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    IMAGE_FILE_NAME NVARCHAR(255) NOT NULL,
    LENGTH INT,
    VIDEO_FILE_NAME NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(MAX),
    USER_ID VARCHAR(36),
    COUNTRY_ID VARCHAR(36),
    FOREIGN KEY (USER_ID) REFERENCES [User](ID),
    FOREIGN KEY (COUNTRY_ID) REFERENCES Country(ID)
);

CREATE TABLE Movie_Genre (
    MOVIE_ID INT NOT NULL,
    GENRE_ID INT NOT NULL,
    PRIMARY KEY (MOVIE_ID, GENRE_ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES Movie(ID),
    FOREIGN KEY (GENRE_ID) REFERENCES Genre(ID)
);

CREATE TABLE Comment (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    MOVIE_ID INT NOT NULL,
    COMMENTED_AT DATETIME2 NOT NULL,
    COMMENT NVARCHAR(MAX) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES [User](ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES Movie(ID),
    CONSTRAINT UQ_Comment_Unique UNIQUE (USER_ID, MOVIE_ID, COMMENTED_AT)
);
