CREATE TABLE Movie_Hero_Slot (
    ID VARCHAR(36) PRIMARY KEY,
    MOVIE_ID INT NOT NULL,
    SLOT_NAME VARCHAR(50),
    FOREIGN KEY (MOVIE_ID) REFERENCES Movie(ID),
    START_TIME DATETIME,
    END_TIME DATETIME
);