CREATE TABLE Favorite(
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    MOVIE_ID INT NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    CONSTRAINT fk_favorite_user FOREIGN KEY (USER_ID) REFERENCES [User](ID),
    CONSTRAINT fk_favorite_movie FOREIGN KEY (MOVIE_ID) REFERENCES Movie(ID),
    CONSTRAINT uk_favorite_user_movie UNIQUE (USER_ID, MOVIE_ID)
);