pipeline {
    agent any

    environment {
        IMAGE_NAME = 'movie-image:latest'
        CONTAINER_NAME = 'movie-api'
        PORT = '80'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Phuong22122003/Movie-web.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME} back-end"
                // docker.build(IMAGE_NAME)
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh "docker rm -f ${CONTAINER_NAME} || true"

                    sh """
                        docker run -d --name ${CONTAINER_NAME} -p ${PORT}:${PORT} \\
                        -e PORT=${PORT} \\
                        -e DB_CONNECTION_URL="jdbc:sqlserver://host.docker.internal:1433;databaseName=Movie;encrypt=true;trustServerCertificate=true" \\
                        -e DB_CONNECTION_USERNAME=sa \\
                        -e DB_CONNECTION_PASSWORD=123456789 \\
                        -e UPLOAD_DIR=File \\
                        ${IMAGE_NAME}
                    """
                }
            }
        }
    }

    post {
        success {
            echo "App is deployed and running at http://<your-jenkins-ip>:${PORT}"
        }
        failure {
            echo 'Build or deployment failed'
        }
    }
}
