pipeline {
    agent any

    environment {
        IMAGE_NAME = "movie-image"
        CONTAINER_NAME = "movie-api"
        PORT = "80"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Phuong22122003/Movie-web.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(IMAGE_NAME)
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Stop and remove old container if it exists
                    sh "docker rm -f ${CONTAINER_NAME} || true"

                    // Run the new container
                    sh """
                        docker run -d --name ${CONTAINER_NAME} -p ${PORT}:${PORT} ${IMAGE_NAME}
                    """
                }
            }
        }
    }

    post {
        success {
            echo "✅ App is deployed and running at http://<your-jenkins-ip>:${PORT}"
        }
        failure {
            echo "❌ Build or deployment failed"
        }
    }
}
